version: '3'

vars:
  BINARY_NAME: weChatGPT
  WECHAT_TOKEN:
  REMOTE_ADDRESS:

tasks:
  clean:
    cmds:
      - rm -rf dist
      - mkdir -p dist
  build:
    label: build-{{.TASK}}
    cmds:
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOMIPS={{.GOMIPS}} \
        CGO_ENABLED=0 \
        go build -trimpath -o ./dist/{{.BINARY_NAME}} \
        -ldflags "-X 'main.wxToken={{.WECHAT_TOKEN}}' -w -s -buildid="
      - scp -r ./dist/weChatGPT {{.REMOTE_ADDRESS}}
  linux-amd64:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64
        }
  default:
    cmds:
      - task: clean
      - task: linux-amd64